### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by mkhan45** [mkhan45/RustScript2#6]
To start out with, we want

- [X] Basic expression eval
- [X] Tuples
- [X] Pattern matching variable bindings
- [X] Lambdas
- [X] Basic CLI/REPL
- [x] Lists
- [X] Match expression (a9981e148f586e)
- [X] _ pattern #12 
- [X] Match guards #14 
- [X] Comments #7
- [X] Block expressions #7 
- [x] Maps #19 
- [X] Tail Call Optimization #10 
- [X] Strings #33 
- [x] Atoms #27 
- [X] Good error messages (mostly fixed by 391eea8, though better ones would be nice)

Eventually it would be cool to have:
- [ ] An AST optimization pass
    - [x] Function inlining
    - [x] Convert atoms to ints #27 
    - [x] Convert idents to ints (should be a ~25% perf boost) (ad4b298e333b)
    - [ ] Inline simple assignments to an existing variable, or assignments which are only used once
- [x] A pipe operator (b011436)
    - [X] Function Captures
- [ ] A module/import system with multiple file support
- [x] A web server module in the stdlib
- [ ] Records/named tuples
- [ ] Macros
- [ ] Named/optional arguments?

**Comment by mkhan45** [comment]
We also need proper error messages, to start out we'd have to revamp the scanner so that we can pass line number and maybe column information to the parser

**Comment by mkhan45** [comment]
I've considered it don't think we should have variadic lambdas anymore. They're significantly slower than just having multiple functions unless we implement it as syntax sugar, which has other problems. Since we have a match expression already it also seems a bit excessive and doesn't work well with the `let name = fn(args) => expr` syntax

**Comment by mkhan45** [comment]
currying might cause hard to debug errors, since error reporting is pretty minimal right now

**Comment by mkhan45** [comment]
Inlining functions at preprocess time might be impossible since little is known about the functions called. However, it might be possible at runtime on a block by block basis

**Comment by mkhan45** [comment]
it might be possible to make a non tail recursive function tail recursive via ast transformation to use an accumulator in simple cases or by adding a stack accumulator in more complicated ones
